#!/bin/sh

usage="urxvtdo [-ioe] [-g GEOMETRY] [--] CMD [ARGS ...]"

geom=""
fds=""

while getopts 'ioeg:h' optchar; do
    case "$optchar" in
        i) fds="$fds -i" ;;
        o) fds="$fds -o" ;;
        e) fds="$fds -e" ;;
        g) geom="-xrm '*transient-for: 0' -geometry $OPTARG" ;;
        h) echo "$usage"; exit 0 ;;
    esac
done

shift $(expr $OPTIND - 1)

if [ -z "$1" ]; then
    echo "$usage" >&2
    exit 1
fi

cmd="$@"

parpty $fds "urxvt -pty-fd \$0 $geom" $cmd
